name: News Summary Email

on:
  schedule:
    # 매일 아침 9시 UTC에 실행 (UTC를 기준으로 하므로 지역에 맞게 조정 필요)
    - cron: '30 23 * * *'

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script to send email
      run: python ins_dx_newsletter_v2.1.py
      env:
             MY_OPEN_API_KEY: ${{secrets.MY_OPEN_API_KEY}}
             X_NAVER_CLIENT_ID: ${{secrets.X_NAVER_CLIENT_ID}}
             X_NAVER_CLIENT_SECRET: ${{secrets.X_NAVER_CLIENT_SECRET}}
             NAVER_ID: ${{secrets.NAVER_ID}}
             NAVER_PASSWORD: ${{secrets.NAVER_PASSWORD}}


    - name: commits
      run: |
        git config --global user.email "mi_digital@naver.com"
        git config --global user.name "Digital New Business Team"
        git add newsletter.html
        git commit -m "뉴스데이터 요약 & 뉴스레터 생성"

