name: News Summary Email

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # 매일 아침 9시 UTC에 실행 (UTC를 기준으로 하므로 지역에 맞게 조정 필요)
    - cron: '55 18 * * *'

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script to send email
      run: python ins_dx_newsletter_v2.1.py
      env:
             OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
             CLIENT_ID: ${{secrets.CLIENT_ID}}
             CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
             EMAIL_ID: ${{secrets.EMAIL_ID}}
             EMAIL_PW: ${{secrets.EMAIL_PW}}


    - name: commits
      run: |
        git config --global user.email "mi_digital@naver.com"
        git config --global user.name "Digital New Business Team"
        git add newsletter.html
        git commit -m "뉴스데이터 요약 & 뉴스레터 생성"

